# Generated by Django 5.1.7 on 2025-04-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vox',
            name='image',
            field=models.ImageField(default="{%static 'image/avesham.jpg' %}", upload_to='movies/'),
        ),
        migrations.AddField(
            model_name='vox',
            name='showtime',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
