# Generated by Django 5.1.7 on 2025-04-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0002_vox_image_vox_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vox',
            name='image',
            field=models.ImageField(null=True, upload_to='movies/'),
        ),
    ]
