# Generated by Django 5.1.7 on 2025-05-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vox',
            name='screen',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
