# Generated by Django 5.1.7 on 2025-05-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0005_vox_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vox',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
