# Generated by Django 5.1.7 on 2025-05-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0006_vox_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_per_ticket',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
