# Generated by Django 5.1.7 on 2025-05-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0007_booking_price_per_ticket_booking_ticket_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ticket_count',
            new_name='tickets',
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_per_ticket',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
