# Generated by Django 5.1.7 on 2025-05-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0008_rename_ticket_count_booking_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vox',
            name='trailer_file',
            field=models.FileField(blank=True, null=True, upload_to='trailers/'),
        ),
        migrations.AddField(
            model_name='vox',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
