# Generated by Django 5.1.7 on 2025-05-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0009_vox_trailer_file_vox_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vox',
            name='trailer_file',
        ),
    ]
